name: Send messages

on:
  push:
  schedule:
    - cron: "0 16 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - name: Send
        run: npm run send
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
